name: Deploy via SSH

on:
  push:
    branches:
      - main  # adjust branch if needed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            cd /var/www/database
            git pull
            go mod tidy
            reboot
